#!/bin/bash
# Claude Code Wrapper Script with pseudo-TTY and file-based output

export HOME=/root
export PATH="/usr/local/bin:$PATH"
export USER=root
export TERM=xterm-256color

# Disable Claude Code's internal cron so sessions launched through this
# wrapper rely on external cron instead.
export CLAUDE_CODE_DISABLE_CRON=1

# Use the repo-local settings.json (generated by the orchestrator).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SETTINGS_FILE="$SCRIPT_DIR/settings.json"

# Create a temp file for output
TMPFILE=$(mktemp)
trap "rm -f $TMPFILE" EXIT

# Build properly quoted command
QUOTED_ARGS=""
for arg in "$@"; do
    # Escape single quotes in the argument and wrap in single quotes
    escaped_arg=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
    QUOTED_ARGS="$QUOTED_ARGS '$escaped_arg'"
done

# Locate the claude binary (npm global install location varies by environment)
CLAUDE_BIN=""
for candidate in "/root/.local/bin/claude" "/usr/local/bin/claude" "/usr/bin/claude" "$(which claude 2>/dev/null)"; do
    if [ -x "$candidate" ]; then
        CLAUDE_BIN="$candidate"
        break
    fi
done

if [ -z "$CLAUDE_BIN" ]; then
    echo "ERROR: claude binary not found. Tried: /root/.local/bin/claude, /usr/local/bin/claude, /usr/bin/claude" >&2
    exit 1
fi

# Run claude with script for pseudo-TTY (using the original binary)
# Include --settings flag to use custom settings file
script -q /dev/null -c "$CLAUDE_BIN --settings $SETTINGS_FILE $QUOTED_ARGS" > "$TMPFILE" 2>&1

# Clean and output the result (remove ANSI codes, OSC sequences, and control chars)
cat "$TMPFILE" | tr -d '\r' | sed 's/\x1b\[[0-9;]*[a-zA-Z]//g; s/\x1b\[[?][0-9]*[a-zA-Z]//g; s/\x1b\[<u//g; s/\x1b\][0-9]*;[^\x07]*\x07//g'
